name = "Apollo"
author = "Lunar Starstrum <lunar@forsaken-borders.net>"
version = "1.8.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ea8432491eb18745f31613e6d8c24535936bae3896f6006e0cd2fd84fe8d845"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
