name = "Apollo"
author = "Lunar Starstrum <lunar@forsaken-borders.net>"
version = "1.8.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86d9bde308b994aa6e97472a287cd5dbbe1bc521b613e6df65c5ffb8bd827079"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
