name = "Apollo"
author = "Lunar Starstrum <lunar@forsaken-borders.net>"
version = "1.8.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5dc514834c42c5f27416a2874d357ea37137d3806bc2247f1118959830667ff9"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
