name: Update Modpack

on:
    schedule:
        # Once every two weeks
      - cron: "0 0 */14 * *"

jobs:
  update:
    name: Update Modpack
    runs-on: ubuntu-latest
    outputs:
      updated: ${{ steps.update-mods.outputs.updated }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: go install github.com/packwiz/packwiz@latest
      - name: Update Mods and Mod Loaders
        id: update-mods
        run: ${{ github.workspace }}/.github/scripts/update-mods.sh
  process-commit:
      needs: update
      if: needs.update.outputs.updated == 'true'
      uses: ./.github/workflows/process-commit.yml
      secrets:
        MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}